import { ROLE_MAP } from '@adp/shared'

export default [
  {
    firstname: 'Martin',
    lastname: 'Facciuto',
    email: 'martin_facciuto@hotmail.com',
    telephone: '1234567',
    password: '123',
    role: ROLE_MAP.ADMIN,
  },
  {
    firstname: 'Andres',
    lastname: 'Gomez',
    email: 'andresgomezic@gmail.com',
    telephone: '1234567',
    password: '123',
    role: ROLE_MAP.ADMIN,
  },
  {
    firstname: 'Lucas',
    lastname: 'Lezano',
    email: 'lukitaslezano@gmail.com',
    telephone: '1234567',
    password: '123',
    role: ROLE_MAP.ADMIN,
  },
  {
    firstname: 'Pablo',
    lastname: 'Kass',
    email: 'kasspablo@gmail.com',
    telephone: '1234567',
    password: '123',
    role: ROLE_MAP.ADMIN,
  },
  {
    firstname: 'Matias',
    lastname: 'Facciuto',
    email: 'tute@adp.com',
    telephone: '1234567',
    password: '123',
    role: ROLE_MAP.ADMIN,
  },
  {
    firstname: 'Daniel',
    lastname: 'Palacios',
    email: 'dpalacios@adp.com',
    telephone: '1234567',
    password: '123',
    role: ROLE_MAP.ADMIN,
  },
  {
    firstname: 'Emiliano',
    lastname: 'Reparaz',
    email: 'elreparaz31@gmail.com',
    telephone: '1234567',
    password: '123456789',
    role: ROLE_MAP.ADMIN,
  },
]
