export const PERMISSION_MAP = {
  ROLE_READ: 'role:read',
  ROLE_CREATE: 'role:create',
  ROLE_UPDATE: 'role:update',
  ROLE_DELETE: 'role:delete',
  PERMISSION_READ: 'permission:read',
  PERMISSION_CREATE: 'permission:create',
  PERMISSION_UPDATE: 'permission:update',
  PERMISSION_DELETE: 'permission:delete',
  STAGE_STATE_READ: 'stageState:read',
  STAGE_STATE_CREATE: 'stageState:create',
  STAGE_STATE_UPDATE: 'stageState:update',
  STAGE_STATE_DELETE: 'stageState:delete',
  PROJECT_STATE_READ: 'projectState:read',
  PROJECT_STATE_CREATE: 'projectState:create',
  PROJECT_STATE_UPDATE: 'projectState:update',
  PROJECT_STATE_DELETE: 'projectState:delete',
  PROJECT_READ: 'project:read',
  PROJECT_CREATE: 'project:create',
  PROJECT_UPDATE: 'project:update',
  PROJECT_DELETE: 'project:delete',
  STAGE_READ: 'stage:read',
  STAGE_CREATE: 'stage:create',
  STAGE_UPDATE: 'stage:update',
  STAGE_DELETE: 'stage:delete',
  PROJECT_NOTE_CREATE: 'projectNote:create',
  PROJECT_NOTE_READ: 'projectNote:read'
}

export const PERMISSION_ARRAY = Object.values(PERMISSION_MAP)
