export const FRONT_PATH = '../../frontend'

export const TABLES = {
  AREA_AVERAGE_COMPLETITION: 'area_acps',
  AREA: 'areas',
  CACHE: 'caches',
  CHECK: 'checks',
  CHECKLIST: 'checklists',
  CONFIGURATION: 'configurations',
  CONTACT_PROJECT: 'contact_projects',
  CONTACT_STAGE: 'contact_stages',
  CONTACT_USER: 'contact_users',
  CONTACT: 'contacts',
  NOTIFICATION: 'notifications',
  PERMISSION: 'permissions',
  PROJECT_NOTE: 'project_notes',
  PROJECT: 'projects',
  ROLE_PERMISSION: 'role_permissions',
  ROLE: 'roles',
  SESSION: 'sessions',
  STAGE_NOTE: 'stage_notes',
  TASK_STATE: 'task_states',
  STAGE: 'stages',
  TOKEN: 'tokens',
  USER_AVERAGE_COMPLETITION: 'user_acps',
  USER_FINISHED_PROJECT: 'usr_fin_prs',
  USER_FINISHED_STAGE: 'usr_fin_sts',
  USER_NOTIFICATION: 'user_notifications',
  USER: 'users',
}
