export const FRONT_PATH = '../../frontend'

export const TABLES = {
  AREA_AVERAGE_COMPLETITION: 'area_acps',
  AREA: 'areas',
  CACHE: 'caches',
  CHECK: 'checks',
  CHECKLIST: 'checklists',
  CONFIGURATION: 'configurations',
  CONTACT_PROJECT: 'contact_projects',
  CONTACT_STAGE: 'contact_stages',
  CONTACT_USER: 'contact_users',
  CONTACT: 'contacts',
  FILE_RECORD: 'file_records',
  NOTIFICATION: 'notifications',
  PERMISSION: 'permissions',
  PROJECT_NOTE_FILE: 'project_note_files',
  PROJECT_NOTE: 'project_notes',
  PROJECT: 'projects',
  ROLE_PERMISSION: 'role_permissions',
  ROLE: 'roles',
  SESSION: 'sessions',
  STAGE_NOTE_FILE: 'stage_note_files',
  STAGE_NOTE: 'stage_notes',
  TASK_STATE: 'task_states',
  STAGE: 'stages',
  TOKEN: 'tokens',
  USER_AVERAGE_COMPLETITION: 'user_acps',
  USER_FINISHED_PROJECT: 'usr_fin_prs',
  USER_FINISHED_STAGE: 'usr_fin_sts',
  USER_NOTIFICATION: 'user_notifications',
  USER: 'users',
}

export const MODELS = {
  AREA_AVERAGE_COMPLETITION: 'AreaAverageCompletion',
  AREA: 'Area',
  CACHE: 'Cache',
  CHECK: 'Check',
  CHECKLIST: 'Checklist',
  CONFIGURATION: 'Configuration',
  CONTACT_PROJECT: 'ContactProject',
  CONTACT_STAGE: 'ContactStage',
  CONTACT_USER: 'ContactUser',
  CONTACT: 'Contact',
  FILE_RECORD: 'FileRecord',
  NOTIFICATION: 'Notification',
  PERMISSION: 'Permission',
  PROJECT_NOTE_FILE: 'ProjectNoteFile',
  PROJECT_NOTE: 'ProjectNote',
  PROJECT: 'Project',
  ROLE_PERMISSION: 'RolePermission',
  ROLE: 'Role',
  SESSION: 'Session',
  STAGE_NOTE_FILE: 'StageNoteFile',
  STAGE_NOTE: 'StageNote',
  TASK_STATE: 'TaskState',
  STAGE: 'Stage',
  TOKEN: 'Token',
  USER_AVERAGE_COMPLETITION: 'UserAverageCompletion',
  USER_FINISHED_PROJECT: 'UserFinishedProject',
  USER_FINISHED_STAGE: 'UserFinishedStage',
  USER_NOTIFICATION: 'UserNotification',
  USER: 'User',
}
